import service from "@/utils/service";

//获取折线图数据
export function queryTrend(data) {
  // return new Promise((resolve, reject) => {
  //   resolve({
  //     status: 0,
  //     message: "success",
  //     data: [
  //       {
  //         name: "在职人数",
  //         list: [
  //           { label: "07-11", value: "0" },
  //           { label: "07-12", value: "0" },
  //           { label: "07-13", value: "0" },
  //           { label: "07-14", value: "0" },
  //           { label: "07-15", value: "0" },
  //           { label: "07-16", value: "1482" },
  //           { label: "07-17", value: "1433" }
  //         ]
  //       }
  //     ]
  //   });
  //  })
  return service({
    url: "/oper/atte/linechart",
    method: "post",
    data: data // body参数
  });
 
}


export function queryList(data) {
  // return new Promise((resolve, reject) => {
  //   resolve({
  //     status: 0,
  //     message: "success",
  //     data: {
  //       page: { total: 25, totalPage: 2, pageSize: 20, pageNum: 1 },
  //       thead: [
  //         {
  //           prop: "orgName",
  //           label: "区域",
  //           sortable: false,
  //           click: true,
  //           defaultSort: false,
  //           sortNo: 1,
  //           show: true
  //         },
  //         {
  //           prop: "total",
  //           label: "总人数",
  //           sortable: true,
  //           click: false,
  //           defaultSort: false,
  //           sortNo: 2,
  //           show: true
  //         },
  //         {
  //           prop: "retentionRate",
  //           label: "留存率",
  //           sortable: true,
  //           click: false,
  //           defaultSort: true,
  //           sortNo: 3,
  //           show: true
  //         },
  //         {
  //           prop: "momGrowth",
  //           label: "环比增长",
  //           sortable: true,
  //           click: false,
  //           defaultSort: false,
  //           sortNo: 4,
  //           show: true
  //         },
  //         {
  //           prop: "momGrowthRate",
  //           label: "环比增长率",
  //           sortable: true,
  //           click: false,
  //           defaultSort: false,
  //           sortNo: 5,
  //           show: true
  //         },
  //         {
  //           prop: "yoyGrowth",
  //           label: "同比增长",
  //           sortable: true,
  //           click: false,
  //           defaultSort: false,
  //           sortNo: 6,
  //           show: true
  //         },
  //         {
  //           prop: "yoyGrowthRate",
  //           label: "同比增长率",
  //           sortable: true,
  //           click: false,
  //           defaultSort: false,
  //           sortNo: 7,
  //           show: true
  //         }
  //       ],
  //       tbody: [
  //         {
  //           orgLevel: 2,
  //           orgCode: "",
  //           orgName: "全国",
  //           total: 1433,
  //           retentionRate: "62.58%",
  //           momGrowth: -84,
  //           momGrowthRate: "-3.54%",
  //           yoyGrowth: -133,
  //           yoyGrowthRate: "-5.49%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "1027",
  //           orgName: "山东省区",
  //           total: 132,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "1061",
  //           orgName: "四川省区",
  //           total: 44,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2177",
  //           orgName: "福建省区",
  //           total: 88,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2179",
  //           orgName: "湖北省区",
  //           total: 88,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2278",
  //           orgName: "河北省区",
  //           total: 44,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2279",
  //           orgName: "山西省区",
  //           total: 44,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2280",
  //           orgName: "内蒙古省区",
  //           total: 22,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2281",
  //           orgName: "广东省区",
  //           total: 132,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2283",
  //           orgName: "海南省区",
  //           total: 44,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2286",
  //           orgName: "江西省区",
  //           total: 66,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2287",
  //           orgName: "安徽省区",
  //           total: 66,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2288",
  //           orgName: "浙江省区",
  //           total: 176,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2290",
  //           orgName: "辽宁省区",
  //           total: 66,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2291",
  //           orgName: "吉林省区",
  //           total: 22,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2292",
  //           orgName: "黑龙江省区",
  //           total: 22,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2293",
  //           orgName: "河南省区",
  //           total: 66,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2294",
  //           orgName: "湖南省区",
  //           total: 44,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2297",
  //           orgName: "贵州省区",
  //           total: 22,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         },
  //         {
  //           orgLevel: 2,
  //           orgCode: "2470",
  //           orgName: "广西省区",
  //           total: 44,
  //           retentionRate: "62.86%",
  //           momGrowth: 0,
  //           momGrowthRate: "0.00%",
  //           yoyGrowth: 0,
  //           yoyGrowthRate: "0.00%",
  //           activeCount: null,
  //           entryCount: null,
  //           entryRate: null,
  //           dimissionCount: null,
  //           dimissionRate: null,
  //           lessThanOneCount: null,
  //           lessThanOneRate: null,
  //           moreThanOneCount: null,
  //           moreThanOneRate: null,
  //           averageAge: null,
  //           overAge: null,
  //           daZhuan: null,
  //           daZhuanAbove: null,
  //           man: null,
  //           women: null,
  //           mainSource: null,
  //           mainSourceCount: null,
  //           moreThanOneEmpRate: null,
  //           secondSource: null,
  //           secondSourceCount: null,
  //           moreThanOneWorkRate: null,
  //           moreSourcEmpRate: null,
  //           name: null,
  //           workmonth: null,
  //           sex: null,
  //           zgxl: null,
  //           age: null,
  //           cHrZpqd: null,
  //           emplid: null
  //         }
  //       ]
  //     }
  //   });
  // })
  return service({
    url: "/oper/atte/details",
    method: "post",
    data: data // body参数
  });
}
